### ISSUE TITLE
This is a concept, not a section

### ISSUE THREAD

**Issue by langsamu** [ukparliament/parliament.uk-things#171]
[This copy](https://devci.parliament.uk/concepts/AIg8zyho) is misleading.
Maybe with collections soon we can comfortably rename it.

https://github.com/ukparliament/parliament.uk-things/blob/223e4dc310f013f8325c3fca85d6b0ce55cb1174/app/views/concepts/show.html.haml#L10

**Comment by jakemulley** [comment]
Resolved thanks to @joshuawaheed :-)
